apiVersion: v1
kind: Service
metadata:
  name: jwt-issuer
  namespace: kafka
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: jwt-issuer
  type: LoadBalancer