apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: wurstmeister/kafka:2.11-2.0.0
        ports:
        - containerPort: 9092
        env:
        - name: DOCKER_API_VERSION
          value: 1.22
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: 'zookeeper:2181'
        - name: KAFKA_LISTENERS
          value: 'PLAINTEXT://kafka:9092'
        - name: KAFKA_ADVERTISED_LISTENERS
          value: 'PLAINTEXT://kafka:9092'
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"