apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-consumer
  namespace: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-consumer
  template:
    metadata:
      labels:
        app: kafka-consumer
    spec:
      containers:
      - name: kafka-consumer
        image: ghcr.io/tom9eiger/kafka-consumer:latest
        ports:
        - containerPort: 9092
        env:
        - name: KAFKA_BROKER_URL
          value: kafka-service:29092
        - name: KAFKA_TOPIC
          value: test-topic
