apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: kafka
spec:
  ports:
  - port: 9092
    name: kafka
    targetPort: 9092
  - port: 29092
    name: kafka-external
    targetPort: 29092
  selector:
    app: kafka
