apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kafka
  namespace: kafka
spec:
  hosts:
  - "kafka-service.kafka.svc.cluster.local"
  tcp:
  - match:
    - port: 29092
    route:
    - destination:
        host: kafka-service
        port:
          number: 29092
