apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: kafka
  namespace: kafka
spec:
  host: kafka-service
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL
    loadBalancer:
      simple: ROUND_ROBIN
