apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: kafka-jwt
  namespace: kafka
spec:
  selector:
    matchLabels:
      app: kafka-consumer
  jwtRules:
  - issuer: "http://jwt-issuer.jwt-issuer-namespace.svc.cluster.local"
    jwksUri: "http://jwt-issuer.jwt-issuer-namespace.svc.cluster.local:3000/.well-known/jwks.json"