name: Build and Deploy JWT Issuer

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate RSA keys
        run: |
          mkdir -p keys
          openssl genpkey -algorithm RSA -out keys/private_key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in keys/private_key.pem -out keys/public_key.pem

      - name: Convert Public Key to JWKS
        run: |
          npm install -g pem-jwk
          cat keys/public_key.pem | pem-jwk > keys/jwks.json

      - name: Build Docker image
        run: |
          docker build -t <your-docker-registry>/jwt-issuer:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker push <your-docker-registry>/jwt-issuer:latest

      - name: Deploy to Kubernetes
        uses: azure/k8s-deploy@v1
        with:
          namespace: kafka
          manifests: |
            jwt-issuer-deployment.yaml
            jwt-issuer-service.yaml
