name: Build and Deploy JWT Issuer

on:
  push:
    branches:
      - main
    paths:
      - 'kafka-jwt/**'
      - '.github/workflows/build-and-push-jwt.yaml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate RSA keys
        run: |
          mkdir -p keys
          openssl genpkey -algorithm RSA -out keys/private_key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in keys/private_key.pem -out keys/public_key.pem

      - name: Convert Public Key to JWKS
        run: |
          cd kafka-jwt
          npm install -g pem-jwk
          cat keys/public_key.pem | pem-jwk > keys/jwks.json

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./kafka-jwt
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/kafka-jwt:latest
