name: Build and Deploy JWT Issuer

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate RSA keys
        run: |
          mkdir -p jwt-issuer/keys
          openssl genpkey -algorithm RSA -out jwt-issuer/keys/private_key.pem -pkeyopt rsa_keygen_bits:2048
          openssl rsa -pubout -in jwt-issuer/keys/private_key.pem -out jwt-issuer/keys/public_key.pem

      - name: Convert Public Key to JWKS
        run: |
          cd jwt-issuer
          npm install -g pem-jwk
          cat keys/public_key.pem | pem-jwk > keys/jwks.json

      - name: Build Docker image
        run: |
          cd jwt-issuer
          ls -l
          docker build -t ghcr.io/${{ github.repository }}/jwt-issuer:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          cd jwt-issuer
          docker push ghcr.io/${{ github.repository }}/jwt-issuer:latest
