name: Build and Push Kafka Consumer

on:
  push:
    branches:
      - main
    paths:
      - 'kafka-consumer/**'
      - '.github/workflows/build-and-push-consumer.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./kafka-consumer
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/kafka-consumer:latest

    # - name: Verify image
    #   run: |
    #     docker run --rm ghcr.io/${{ github.repository_owner }}/kafka-consumer:latest python kafka_consumer.py
