name: Build and Push JWT Issuer

on:
  push:
    branches:
      - main
    paths:
      - 'jwt-issuer/**'
      - '.github/workflows/build-and-push-jwt.yaml'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./jwt-issuer
        push: true
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/jwt-issuer:latest

    - name: Verify image
      run: |
        docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/jwt-issuer:latest node server.js
